version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/backend-project
permissions:
  - object: /var/www/backend-project
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ubuntu