version: 0.2

phases:
  install:
    runtime-versions:
      java: 17
  build:
    commands:
      - echo Build started on `date`
      - chmod +x ./gradlew
      - ./gradlew build -x test
  post_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 879772956301.dkr.ecr.us-east-1.amazonaws.com
      - echo Pushing to ECR...
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - REPOSITORY_URI=879772956301.dkr.ecr.us-east-1.amazonaws.com/user134-backend-repo
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:latest
      - printf '[{"name":"backend-container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - deployment.yaml
    - service.yaml
