apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "password1234" # 나중에 보안을 위해 수정하세요
            - name: MYSQL_DATABASE
              value: "bookdb"
          ports:
            - containerPort: 3306
